### ISSUE TITLE
Поддержка элемента <param>

### ISSUE THREAD

**Issue by av3nger** [av3nger/market-exporter#17]
Добавить возможность выбирать какие атрибуты будут выгружаться в элемент <param>.
Например, <param name="цвет">расный<param>

**Comment by Sanuich** [comment]
$tax_attrs_t = wc_get_attribute_taxonomies();
			$tax_attrs = array();
			foreach($tax_attrs_t as $attr)
			{
				$tax_attrs[$attr->attribute_name]=$attr->attribute_label;
			}
while ( $variation_count > 0 ):
				$variation_count--;
.....................
//sanuich params. Tested on yandex 2016-10-16
				if(!empty($variable_attribute)){
					$attrs = $product->get_attributes();
					foreach($attrs as $key=>$attr)
					{
						if($attr['is_taxonomy']==1)
						{
							$terms = array();
							$terms_t = get_the_terms( $product->id, $key );
							foreach($terms_t as $term)
							{
								$terms[$term->slug]=$term->name;
							}
							
							$yml.="<param name=\"".$tax_attrs[str_replace("pa_","",$key)]."\">".$terms[$variable_attribute['attribute_'.$key]]."</param>".PHP_EOL;
						}
						else
						{
							$yml.="<param name=\"".$attr['name']."\">".$variable_attribute['attribute_'.$key]."</param>".PHP_EOL;
						}
					}
				}

**Comment by Sanuich** [comment]
добавить опцию в настройках
"импортировать варианты для вариативных товаров"
да, только база, нет

**Comment by av3nger** [comment]
С атрибутами не все так просто. Нельзя все подряд выгружать в качестве атрибутов. Нужно давать возможность выбирать.

А что значит выгружать только базу или все вариативные товары? В базе же не у всех все расписано и она может не содержать всей необходимой информации

**Comment by Sanuich** [comment]
База, имеется ввиду - базовый товар без его вариаций. Нужно в настройках для начала сделать опцию - выгружать с параметрами или без. 
Или опция - выгружать все вариации товара с параметрами.
Я думаю что нет необходимости давать возможность выбирать параметры. Они обычно и так самые необходимые. Если в яндекс маркет и попадет какой то лишний параметр то это не страшно.

**Comment by Sanuich** [comment]
Понимаю. Делать что то универсальное можно всю жизнь. А вставить код типа моего и добавть галочку - выгружать атрибуты или нет и дать юзеру решать : нужно ли оно ему в таком виде, можно сейчас. А там кто то что то еще предложит.

**Comment by vguns** [comment]
Sanuich спасибо за код! Подскажите как передать стандартные параметры вес и габариты?

**Comment by av3nger** [comment]
Я вряд ли Вам в одну строчку смогу это объяснить ) Но постараюсь реализовать

**Comment by Sanuich** [comment]
Все довольно просто.
Достаточно посмотреть файл wp-content\plugins\woocommerce\templates\single-product\product-attributes.php

Не буду выкладывать куски кода - выложу ссылку на архив обновленного файла
 wp-content\plugins\market-exporter-master\admin\class-market-exporter-wc.php

ССЫЛКА >>> ukrmoda.com.ua/class-market-exporter-wc.zip

Габариты, вес и атрибуты невариативного товара выглядят точно как на закладке "Дополнительная информация"
Если нужно что то изменить - пишите не стесняйтесь
sancuich@gmail.com
проверяйте, пишите

**Comment by av3nger** [comment]
обновление 0.3.2 beta решает данные проблемы
