### ISSUE TITLE
Теги в <description>

### ISSUE THREAD

**Issue by dfkkg** [av3nger/market-exporter#22]
1. У меня почему-то всё описание в description оборачивается в <![CDATA[....]]
2. Некоторые описания содержат теги (в моём случае - strong), а выгружать в Маркет текст нужно без тегов. Не плохо было бы делать strip_tags
![2016-06-17_11-29](https://cloud.githubusercontent.com/assets/19991210/16144961/f05af63c-347e-11e6-9077-10c5d6bfa85d.jpg)

**Comment by av3nger** [comment]
изначально было с strip_tags, многие просили выгружать с CDATA.

**Comment by dfkkg** [comment]
То есть такой прайс не нарушает правила, которые касаются тегов? Я просто понятия не имею что такое CDATA

**Comment by av3nger** [comment]
нет, все нормально. по сути, CDATA позволяет в описание вставлять HTML-теги. без CDATA все теги вызывают ошибки.

**Comment by dfkkg** [comment]
Понял, спасибо!
