### ISSUE TITLE
Лишние кавычки

### ISSUE THREAD

**Issue by WaNgeL-SaTaR** [av3nger/market-exporter#23]
После генерации yml файла ссылка на него имеет лишние кавычки, пример:

`<a href="«http://www.site.ru/wp-content/uploads/market-exporter/ym-export-2016-07-21.yml»">http://www.site.ru/wp-content/uploads/market-exporter/ym-export-2016-07-21.yml</a>`

**Comment by av3nger** [comment]
Спасибо, исправлю. #Этот переводчик меня добивает...

**Comment by WaNgeL-SaTaR** [comment]
Супер! *Переводчики они такие...
