### ISSUE TITLE
Возможность генерации нового yml файла после обновления товаров

### ISSUE THREAD

**Issue by WaNgeL-SaTaR** [av3nger/market-exporter#24]
Было бы интересно увидеть функционал такого плана:

Юзерстори:
После добавления\обновления\может быть раз в день нового товара делать перегенерацию yml файла с тем же именем - это позволит автоматизировать процесс для многих площадок, так как у них есть возможность "пересобирать" информацию по одной и той же ссылке.

**Comment by av3nger** [comment]
Это уже реализовано. По умолчанию файл автоматически генерируется заново раз в сутки

**Comment by WaNgeL-SaTaR** [comment]
Я так понимаю он генерируется со штампом даты, вида - `ym-export-2016-07-21.yml`? 
Возможно ли перезаписывать один и тот же файл с одним и тем же именем, типа `yml-export.yml`?

**Comment by av3nger** [comment]
да, в опциях плагина можно убрать дату. тогда файл будет просто yml-export.yml

**Comment by WaNgeL-SaTaR** [comment]
ок, разобрался, можно еще ссылку на настройки на странице выгрузки сделать, будет вообще шикарно.

**Comment by av3nger** [comment]
сделаю в релизе следующем.
