### ISSUE TITLE
local_delivery_cost

### ISSUE THREAD

**Issue by tich31337** [av3nger/market-exporter#28]
Из официальной документации: Ранее local_delivery_cost использовался в формате YML. В настоящее время элемент является устаревшим для этого формата. Использование элемента в YML пока поддерживается Маркетом, однако рекомендуется перейти на элемент delivery-options.

**Comment by av3nger** [comment]
Да, я знаю. в последней версии, которая тут на GitHub, элемент local_delivery_cost уже удален
