### ISSUE TITLE
Проблема с <local_delivery_cost>

### ISSUE THREAD

**Issue by WaNgeL-SaTaR** [av3nger/market-exporter#29]
Яндекс не воспринимает выгрузку с полем вида `<local_delivery_cost/>` - генерируется плагином. 

Отписка яндекса при импорте:

> Доставка по умолчанию показывается в тех случаях, когда не указана стоимость доставки конкретного товара. Пример оформления стоимости доставки по умолчанию: < local_delivery_cost >350<\local_delivery_cost>. Для более гибкой настройки рекомендуется использовать элемент delivery‑options

**Comment by av3nger** [comment]
данной проблемы нет в версии с GitHub
