### ISSUE TITLE
Market Exporter can't be activated

### ISSUE THREAD

**Issue by bisteinoff** [av3nger/market-exporter#30]
After I updated Wordpress, Woocoomers, and Market Exporter to the up-to-date versions, Market Exporter stopped working, and caused error 500. After that I tried to reinstall the plugin, and now it can't be activated. This is what it writes: https://yadi.sk/i/0IOfKtSyzbhLy

How can I solve the problem? Thank you.

**Comment by av3nger** [comment]
Hi!
You need to update PHP to version 5.4 or later. That will resolve the issue

**Comment by trabajo1** [comment]
Hi!
I've tried several versions of PHP (5.4, 5.5, 5.6, 7.0) but it didn't help. 
When I click "Plugins" or "Tools" there is a 500 error.
Version 0.26 is stable.

**Comment by av3nger** [comment]
Are you sure it's related to the Market Exporter plugin? Is WordPress and WooCommere updated to the latest version?

**Comment by trabajo1** [comment]
Я на русском с Вашего позволения. 
Да, абсолютно уверен, если могу как-то помочь отловить/отладить ошибку, с радостью помогу. 
Плагин: https://ru.wordpress.org/plugins/market-exporter/

Версия WC:		2.6.7
Версия WP:		4.6.1
Версия PHP:		 5.4.45 (пробывал разные)

**Comment by av3nger** [comment]
надо error_log с сервера смотреть во время ошибки. сможете выслать? у меня на этих версиях все хорошо работает.

**Comment by trabajo1** [comment]
Да, пришлю, ближе к вечеру....
