### ISSUE TITLE
Функция get_images

### ISSUE THREAD

**Issue by trabajo1** [av3nger/market-exporter#31]
Привет, еще раз) Вопрос по 0.26 версии. 
Мне кажется функция  get_images( $id, $count)  не совсем корректно собирает ссылки. 
Ситуация такая, проблемы две: 
1) создание и первичную разработку сайта я делал на тестовом домене, после того как все доделал перенес на боевой домен (поменяв в настройках WP два URL). При генерации YML-файла ссылку на карточку товара (url/url) скрипт правильно генерирует-уже новую, а ссылки на картинки товара (picture/picture) на старый домен-тестовый.
Видимо, где-то в базе глубоко сидит тестовый домен. 
Но это проблема не критичная, Ctrl+H в помощь.
2) А вот это не совсем понимаю, почему несмотря на то что в настройках плагина параметру $count я присваиваю значение 10 (которое по умолчанию), а в YML все равно попадает одна картинка - один тег для одного товара. Хотя картинок очень много прикрепил к карточке товара.

**Comment by av3nger** [comment]
Я отказался от get_images() в более новых версиях в пользу get_the_post_thumbnail_url(). Изначально я пытался максимально оптимизировать плагин и получать все данные напрямую из базы. Но слишком часто все менялось и пришлось начать использовать функции WordPress и WooCommerce. Но сейчас тоже лишь одно изображение выгружается. В ближайшем обновлении доделаю выгрузку серии изображений.

**Comment by trabajo1** [comment]
Спасибо!
Постараюсь сам немного допилить, поскольку новые версии у меня не устанавливаются)
