### ISSUE TITLE
 Добавить параметры vendor и  model  в выгрузку 

### ISSUE THREAD

**Issue by maxbeer** [av3nger/market-exporter#35]
извините 
<model>
Vendor есть

**Comment by av3nger** [comment]
Добрый день,

Вам нужно в версии с GitHub в настройках задать соответствующие атрибуты, которые отвечают за данные поля

Best regards,
Anton Vanyukov

2 мая 2017 г., в 15:34, maxbeer <notifications@github.com<mailto:notifications@github.com>> написал(а):


подскажите пож как это сделать чтоб избавиться от этого

Производитель присутствует у 0% товарных предложений
Описания товаров присутствуют только у 2% товарных предложений
Название модели присутствует у 0% товарных предложений
