### ISSUE TITLE
Проблема с подкатегориями

### ISSUE THREAD

**Issue by WaNgeL-SaTaR** [av3nger/market-exporter#42]
Окно выбора категории не отображает подкатегории подкатегорий.
Хотя если не выбирать ничего там и экспортить все сразу, то все категории выгружаются и подкатегории тоже.

**Comment by av3nger** [comment]
Здравствуйте,

Я в курсе. Спасибо. Это будет исправлено в следующей версии


28 авг. 2017 г., в 11:24, Taras <notifications@github.com<mailto:notifications@github.com>> написал(а):


Окно выбора категории не отображает подкатегории подкатегорий.
Хотя если не выбирать ничего там и экспортить все сразу, то все категории выгружаются и подкатегории тоже.

**Comment by av3nger** [comment]
Сделано в версии 1.0.0
