### ISSUE TITLE
При удаление параметра, он остается 

### ISSUE THREAD

**Issue by webnetbt** [av3nger/market-exporter#44]
Обновился до версии 1.0.1 и теперь при указание параметра, далее нету возможности его удалить. 
Оставляю поле параметров пустым, а после сохранения оно все равно отображает его. 

З.Ы. Спасибо за отличный плагин.

**Comment by av3nger** [comment]
Поставьте из ветки development. Там исправлено. На днях выпущу. Сейчас один момент тестирую

**Comment by webnetbt** [comment]
И еще есть косяк - Если товар вариативный, то к каждому продукту прописываются все цвета которые присутствуют в вариативности - кажется что это не совсем правильно .

**Comment by av3nger** [comment]
Исправлено
