### ISSUE TITLE
Фильтр категорий

### ISSUE THREAD

**Issue by Ruuv1337** [av3nger/market-exporter#51]
Вероятно не работает фильтр категорий.
На сайте имеется 320 категорий и 17к товаров.
При выгрузке в файл блок категорий (categories) выставляется правильный и туда не попадают категории которые не были указаны и вроде бы все ок., но нет.
В блоке товаров (offers) я наблюдаю, что для товара проставляется categoryId
равным категории которой нет в блоке categories из этого делаю вывод что, фильтр не работает либо не доделан.
PS: И Яндекс тоже не дурак, он проверяет эти иды и выдает что-то вроде:
![yad](https://user-images.githubusercontent.com/31353526/53290300-1905e080-37b3-11e9-9e2e-27a8491a8a9b.png)

Если товар, категория которого отсутствует в списке этого же файла тоже не будет выгружаться, то можно считать это лучший плагин для ЯМ на данным момент.

**Comment by av3nger** [comment]
Он своеобразно работает. Яндекс принимает только одну категорию для товара. На многих сайтах категорий несколько. Например, наушники, беспроводные. Плагин выбирает первую категорию, но это не всегда то что нужно для выгрузки. Нужно экспериментировать с настройками. К сожалению, автоматически предугадать какую категорию надо выгружать нельзя

**Comment by Ruuv1337** [comment]
Мне удалось исправить это, фильтр заработал.
Но при отсутствии выбора категорий для выгрузки (в настройках) товары не выгрузятся в файл.
Может кому пригодится.

Закинуть в папку плагина admin
Переименовать с txt в php.

[class-market-exporter-wc.txt](https://github.com/av3nger/market-exporter/files/2902434/class-market-exporter-wc.txt)
